#!/bin/bash
#


while getopts ":w" opt; do
  case $opt in
    w)
      node_modules/mocha/bin/mocha  --compilers js:babel-register test/*.js test/**/*.js --require should --require test/test_helpers.js --watch
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;
  esac
done


node_modules/mocha/bin/mocha --recursive test --require should --require test/test_helpers.js --compilers js:babel-register
